# Generated by Django 5.2.4 on 2025-07-12 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stope_name', models.CharField(help_text="Unique name for the stope (e.g., 'North Wing Level 5', 'Main Stope A')", max_length=100, unique=True)),
                ('rqd', models.FloatField(help_text='Rock Quality Designation (%)')),
                ('hr', models.FloatField(help_text='Hydraulic Radius')),
                ('depth', models.FloatField(help_text='Depth below surface (m)')),
                ('dip', models.FloatField(help_text='Dip angle (degrees)')),
                ('direction', models.CharField(help_text='Direction (e.g., North, South)', max_length=50)),
                ('undercut_wdt', models.FloatField(help_text='Undercut width (m)')),
                ('rock_type', models.CharField(help_text='Rock type', max_length=50)),
                ('support_type', models.CharField(help_text='Support type', max_length=50)),
                ('support_density', models.FloatField(help_text='Support density')),
                ('support_installed', models.BooleanField(default=False, help_text='Is support installed?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(max_length=20)),
                ('impact_score', models.FloatField()),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.stope')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StopeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stope', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.stope')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeriesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('stope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries', to='core.stope')),
            ],
        ),
    ]
