# Generated by Django 5.2.4 on 2025-07-14 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category', models.CharField(choices=[('blasting', 'Blasting Operations'), ('equipment', 'Heavy Equipment'), ('excavation', 'Excavation Activities'), ('drilling', 'Drilling Operations'), ('loading', 'Material Loading'), ('transport', 'Heavy Transport'), ('water', 'Water-Related Events'), ('vibration', 'External Vibrations'), ('support', 'Support Installation/Maintenance'), ('geological', 'Geological Events'), ('environmental', 'Environmental Factors'), ('other', 'Other Operations')], help_text='Category of operational event', max_length=20)),
                ('severity_level', models.CharField(choices=[('minimal', 'Minimal Impact'), ('low', 'Low Impact'), ('moderate', 'Moderate Impact'), ('high', 'High Impact'), ('severe', 'Severe Impact'), ('critical', 'Critical Impact')], help_text='Severity level for this impact factor', max_length=10)),
                ('base_impact_weight', models.FloatField(help_text='Base impact weight (0.0-10.0 scale)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('duration_multiplier', models.FloatField(default=1.0, help_text='Multiplier for event duration (0.1-5.0)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)])),
                ('proximity_decay_rate', models.FloatField(default=0.1, help_text='Rate of impact decay with distance (0.01-1.0 per meter)', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
                ('temporal_decay_rate', models.FloatField(default=0.05, help_text='Rate of impact decay over time (0.001-0.5 per day)', validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(0.5)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this factor is currently active')),
                ('site_specific', models.BooleanField(default=False, help_text='Site-specific override of default factors')),
                ('mine_site', models.CharField(blank=True, help_text='Specific mine site (if site-specific)', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of this impact factor')),
                ('validation_source', models.CharField(blank=True, help_text='Source of validation (research, field data, expert opinion)', max_length=200)),
                ('last_calibrated', models.DateTimeField(blank=True, help_text='When this factor was last calibrated/validated', null=True)),
                ('calibrated_by', models.CharField(blank=True, help_text='Engineer who last calibrated this factor', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(help_text='User who created this impact factor', max_length=100)),
            ],
            options={
                'verbose_name': 'Impact Factor',
                'verbose_name_plural': 'Impact Factors',
                'ordering': ['event_category', 'severity_level'],
                'indexes': [models.Index(fields=['event_category', 'severity_level'], name='core_impact_event_c_5c40cd_idx'), models.Index(fields=['is_active'], name='core_impact_is_acti_a88715_idx'), models.Index(fields=['site_specific', 'mine_site'], name='core_impact_site_sp_4c6d89_idx'), models.Index(fields=['last_calibrated'], name='core_impact_last_ca_40817f_idx')],
                'unique_together': {('event_category', 'severity_level', 'mine_site')},
            },
        ),
    ]
