# Generated by Django 5.2.4 on 2025-07-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stope',
            name='direction',
            field=models.CharField(choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West'), ('Northeast', 'Northeast'), ('Northwest', 'Northwest'), ('Southeast', 'Southeast'), ('Southwest', 'Southwest')], help_text='Direction (e.g., North, South)', max_length=50),
        ),
        migrations.AlterField(
            model_name='stope',
            name='rock_type',
            field=models.CharField(choices=[('Granite', 'Granite'), ('Basalt', 'Basalt'), ('Obsidian', 'Obsidian'), ('Shale', 'Shale'), ('Marble', 'Marble'), ('Slate', 'Slate'), ('Gneiss', 'Gneiss'), ('Schist', 'Schist'), ('Quartzite', 'Quartzite'), ('Limestone', 'Limestone'), ('Sandstone', 'Sandstone')], help_text='Rock type', max_length=50),
        ),
        migrations.AlterField(
            model_name='stope',
            name='support_type',
            field=models.CharField(choices=[('None', 'None'), ('Rock Bolts', 'Rock Bolts'), ('Mesh', 'Mesh'), ('Shotcrete', 'Shotcrete'), ('Timber', 'Timber'), ('Cable Bolts', 'Cable Bolts'), ('Steel Sets', 'Steel Sets')], help_text='Support type', max_length=50),
        ),
    ]
