# Generated by Django 5.2.4 on 2025-07-12 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_stope_direction_alter_stope_rock_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_feedback', models.BooleanField(help_text='True = helpful/accurate, False = not helpful/inaccurate')),
                ('corrected_text', models.TextField(blank=True, help_text='Optional user-provided correction or additional information', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(help_text='The prediction this feedback relates to', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.prediction')),
                ('stope', models.ForeignKey(help_text='The stope this feedback relates to', on_delete=django.db.models.deletion.CASCADE, related_name='prediction_feedbacks', to='core.stope')),
            ],
            options={
                'verbose_name': 'Prediction Feedback',
                'verbose_name_plural': 'Prediction Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
