# Generated by Django 5.2.4 on 2025-07-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_impactfactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactfactor',
            name='mine_site',
            field=models.CharField(blank=True, help_text='Specific mine site (if site-specific)', max_length=100, null=True),
        ),
    ]
