# Generated by Django 5.2.4 on 2025-07-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_predictionfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Date and time of measurement')),
                ('vibration_velocity', models.FloatField(blank=True, help_text='Peak particle velocity (mm/s)', null=True)),
                ('displacement', models.FloatField(blank=True, help_text='Displacement measurement (mm)', null=True)),
                ('stress', models.FloatField(blank=True, help_text='Stress measurement (MPa)', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Temperature (°C)', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Humidity (%)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries_data', to='core.stope')),
                ('upload_source', models.ForeignKey(blank=True, help_text='Reference to upload batch if data came from file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_points', to='core.timeseriesupload')),
            ],
            options={
                'verbose_name': 'Time Series Data Point',
                'verbose_name_plural': 'Time Series Data Points',
                'ordering': ['-timestamp'],
                'unique_together': {('stope', 'timestamp')},
            },
        ),
    ]
