# Generated by Django 5.2.4 on 2025-07-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_timeseriesdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeseriesdata',
            name='displacement',
        ),
        migrations.AddField(
            model_name='timeseriesdata',
            name='deformation_rate',
            field=models.FloatField(blank=True, help_text='Deformation rate measurement (mm/day)', null=True),
        ),
    ]
