# Generated by Django 5.2.4 on 2025-07-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_featureengineeringconfig_timeseriesdata_and_more'),
    ]

    operations = [
    ]
