# Generated by Django 5.2.4 on 2025-07-13 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_displacement_to_deformation_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('prediction_horizon_days', models.IntegerField(help_text='How many days ahead the model was predicting')),
                ('training_data_count', models.IntegerField()),
                ('validation_data_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Model Performance Metrics',
                'verbose_name_plural': 'Model Performance Metrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuturePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('current', 'Current Status'), ('short_term', 'Short Term (1-3 days)'), ('medium_term', 'Medium Term (1-2 weeks)'), ('long_term', 'Long Term (1+ months)')], default='current', max_length=20)),
                ('prediction_for_date', models.DateTimeField(help_text='Date/time this prediction is for')),
                ('days_ahead', models.IntegerField(default=0, help_text='How many days ahead this prediction is for')),
                ('risk_level', models.CharField(choices=[('stable', 'Stable'), ('slight_elevated', 'Slightly Elevated'), ('elevated', 'Elevated'), ('high', 'High Risk'), ('critical', 'Critical'), ('unstable', 'Unstable')], max_length=20)),
                ('confidence_score', models.FloatField(help_text='Model confidence in this prediction (0.0-1.0)')),
                ('risk_probability', models.FloatField(help_text='Probability of risk occurrence (0.0-1.0)')),
                ('contributing_factors', models.JSONField(default=dict, help_text='Factors that led to this prediction')),
                ('explanation', models.TextField(help_text='Detailed explanation of the prediction')),
                ('recommended_actions', models.TextField(blank=True, help_text='Recommended preventive or corrective actions')),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_predictions', to='core.stope')),
            ],
            options={
                'verbose_name': 'Future Prediction',
                'verbose_name_plural': 'Future Predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('risk_increase', 'Risk Increase'), ('threshold_exceeded', 'Threshold Exceeded'), ('pattern_anomaly', 'Pattern Anomaly'), ('maintenance_due', 'Maintenance Due')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('future_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.futureprediction')),
                ('stope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.stope')),
            ],
            options={
                'verbose_name': 'Prediction Alert',
                'verbose_name_plural': 'Prediction Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='futureprediction',
            index=models.Index(fields=['stope', 'prediction_for_date'], name='core_future_stope_i_ef2979_idx'),
        ),
        migrations.AddIndex(
            model_name='futureprediction',
            index=models.Index(fields=['prediction_type', 'created_at'], name='core_future_predict_33c6ba_idx'),
        ),
    ]
